baseURL: "https://mariel-rs.github.io/"
languageCode: "en-us"
title: "Welcome | Mariel's GitHub page"
theme: hugo-profile

Paginate: 3
#disqusShortname:
googleAnalytics: G-0L93SSK6KP
ignoreErrors: ["error-remote-getjson"]

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

  #   #Dropdown menu
  #   - identifier: dropdown
  #     enable: false
  #     title: Example dropdown menu
  #     name: Side projects
  #     weight: 0
    # - identifier: Dat Lab
    #   title: Dat Lab
    #   name: Dat Lab
    #   url: http://mariel-rs.github.io/datlab
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /blogs
    #   parent: dropdown
    #   weight: 2

params:
  title: "Mariel's Profile"
  description: Mariel's GitHub profile page
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hola, my name is"
    title: "Mariel."
    subtitle: "Problem solver with technology, data, and analytics"
    content: "I enjoy using modern technologies to build solutions that are 
    user-friendly, adaptable, and deliver value. I am certain that a conjunction
    of applied mathematics, data and technology is key for making the world a 
    state-of-the-art place to live."
    image: /images/headshot.jpg
    button:
      enable: false
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/mariel-rs/
        - icon: fab fa-linkedin-in
          url: https://www.linkedin.com/in/amreyes12/
        - icon: fas fa-book
          url: https://mariel-rs.github.io/blogs
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/girl.jpg"
    content: |-
      I am an engineer with an innate taste for technology and applied 
      mathematics. I have over 8 years of combined experience in technical 
      consultancy and software development in the United Kingdom and Mexico. I 
      have a strong interest in making analytical techniques more accessible to 
      organizations with operations challenges and adding value to their 
      business.
      
      I currently work as a solution consultant for an analytics company and I 
      am learning Brazilian Portuguese in my spare time.

    skills:
      enable: true
      title: "These are a few languages/frameworks I've been working with recently:"
      items:
        - "Hugo"
        - "Java"
        - "Maven"
        - "JavaScript"
        - "NodeJS"

  # Experience
  experience:
    enable: true
    items:
      - job: "Solution Consultant II"
        company: "FICO"
        companyUrl: "https://www.fico.com/"
        date: "Aug 2022 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |
          - Implementation of analytics solutions to a range of customers in 
          banking and retail. 
          - Responsible for the full implementation cycle: configuration, 
          data migration, development

          **Tech stack**
          - `FICO's proprietary software` Blaze, Decision Modeler
          - `Java`
          - `JavaScript`
          - `Python`

      - job: "Data consultant"
        company: "Freelance"
        #companyUrl: "https://example.com"
        date: "Nov 2021 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: true
          content: Working as a freelance consultant, feel free to contact me!
        content: |
          - Development of machine learning and mathematical optimization models, 
          heuristic methods and simulations for solving problems. 
          - Data analysis: treatment, exploratory data analysis (EDA), data 
          mining, natural language processing (NLP) and visualizations.
          - Lead instructor of short courses on Data Analysis and Data Science 
          in Python aimed at audiences with little to none programming 
          experience. 

          **Tech stack**
          - `EDA` matplotlib, pandas, seaborn
          - `LaTeX`
          - `Machine Learning` Naive-Bayes classifier for sentiment analysis
          - `NLP` NLTK, TextBlob
          - `statistics` SciPy, statsmodels
          - `Ẁeb development` Hugo

      - job: "Research Assistant"
        company: "The University of Edinburgh"
        companyUrl: "https://www.ed.ac.uk"
        date: "Sep 2021 - Feb 2022"
        featuredLink:
          enable: true
          name: "See the project site"
          url: "https://digitaltwinhub.co.uk/credo/"
        info:
          enable: false
          content: I worked as as Operational Researcher for the National 
            Digital Twin CReDo project.
        content: |
          I worked as an Operational researcher in the CReDo project, a digital
          twin demonstrator that aims to improve climate resilience across
          infrastructure networks. Collaborated with Lars Schewe and Chris Dent
          from the University of Edinburgh, and 
          [Maksims Abalenkovs](http://mabalenk.gitlab.io/) from the Hartree 
          Center.
          
          Project deliverables:
          - Development of connectivity models of each network to assess impact 
          and fault propagation.
          - Development of a mathematical model for defining the best  
          restoration steps for bringing the most sites to operation.
          - Model deployment in Podman containers.

          **Tech stack**
          - `Git`
          - `LaTeX`
          - `Optimization` Cbc solver
          - `Python` NetworkX, pandas, Pyomo
          - `Podman`
        
      - job: "Sr Engineer"
        company: "AspenTech - MX"
        companyUrl: "https://www.aspentech.com"
        date: "Jul 2019 - Oct 2020"
        info:
          enable: true
          content: "Relocated to Mexico City to join the R&D team"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          Lead a team of software developers of a dynamic optimiser used for 
          unifying Supply chain management with Process control solutions. 
          Highlights during this tenure are:

          - Developed modifications to the product core maintaining quality and 
          adding value to end-users.
          - Created example applications used in development testing.
          - Mentored team members on their career development and progression.
          - Provided tier-3 support to implementation engineers and end-users.

          **Tech stack**
          - `AspenTech's proprietary software` DMC3, GDOT, Aspen Unified
          - `C#`
          - `Fortran`
          - `MS PowerBI`
          - `Perforce`
          - `SQLite`

      - job: "Technical Consultant"
        company: "AspenTech - UK"
        companyUrl: "https://www.aspentech.com"
        date: "Jan 2017 - Jul 2019"
        info:
          enable: true
          content: "Relocated to Reading, UK to fill a technical expertise gap 
            in the European market"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          Transferred to AspenTech's EMEA headquarter office and became the 
          subject matter expert in Advanced Process Control (APC) in the region. 
          
          Highlights during this tenure are:
          - Delivered 1098h of training courses to customers in public 
          classrooms and on-site.
          - Created custom training materials for nonlinear control operations. 
          This custom training was delivered to YASREF (Yanbu, Kingdom of Saudi 
          Arabia) and LyondellBasell (Wesseling, Germany).
          - Lead proactive health check visits to improve satisfaction and 
          accelerate customer success.
          - Delivery of consulting services to customers, such as Cepsa (Palos 
          de la Frontera, Spain), Total (Mitteldeustschland, Germany) and
          Elkem Silicones (France).

          **Tech stack**
          - `AspenTech's proprietary software` Aspen Watch, DMCplus, DMC3, IQ, 
          PCWS
          - `OPC` OPC Expert, Matrikon OPC Explorer
          - `Remote desktop` TeamViewer, WebEx
          - `Salesforce`
          - `Virtualization` MS Hyper-V, VMWare

      - job: "Associate Technical Support Consultant"
        company: "AspenTech - MX"
        companyUrl: "https://www.aspentech.com"
        date: "Dec 2013 - Jan 2017"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          Joined the global team of technical consultants assigned to the 
          Advanced Process Control (APC) suite of products. My responsabilities
          involved:
          - Troubleshooting typical usage problems to customers
          - Detection of product defects and escalation to R&D and Product 
          Management
          - Delivery of virtual training courses to customers, e.g. Flint Hills
          Resources, Wacker Chemie
          - Authoring knowledge base articles with technical tips and best 
          practices

          **Tech stack**
          - `AspenTech's proprietary software` Aspen Watch, DMCplus, PCWS
          - `Remote desktop` TeamViewer, WebEx
          - `Virtualization` MS Hyper-V, VMWare

  # Education
  education:
    enable: true
    #index: true
    items:
      - title: "MSc. in Operational Research"
        school:
          name: "The University of Edinburgh"
          url: "https://www.ed.ac.uk/"
        date: "2021"
        GPA: "Merit. 3.7 / 4.0"
        content: |-
          - Awarded a scholarship for postgraduate studies by the Mexican 
          National Council of Science and Technology (CONACYT).
          - Dissertation: Heuristical methods for the airport slot allocation 
          problem. Supervised by 
          [Prof Miguel F. Anjos](https://miguelanjos.com/).
          - Shortlisted for the Sense of Belonging student award 2021, for 
          creating and fostering collaborative networks among the cohort

          **Tech stack**
          - `LaTeX`
          - `Optimization` FICO Xpress, NEOS server
          - `Python` folium, geopandas, Jupyter, matplotplib, NumPy, pandas, 
            Pyomo, seaborn, scikit-learn, SciPy
          - `R` caret, dplyr, ggplot2
          - `Simulation` Simul8

      - title: "BEng. in Chemical Engineering"
        school:
          name: "Universidad Nacional Autónoma de México"
          url: "https://www.unam.mx/"
        date: "2012"
        GPA: "Magna cum laude. 3.7 / 4.0"
        content: |-
          - Women in STEM scholarship holder.
          - Concentration in Project Management and Biotechnology
          - Awarded a study abroad scholarship to study at 
          [University of Technology, Sydney](https://www.uts.edu.au/) sponsored
          by Fundación UNAM and The Coca-Cola Company.
          
          Extracurricular Activities
            - Completed 480h of volunteering work in a Teacher's training 
            program. Delivered lectures, ran tutorial sessions and maintained a 
            website with assignments and revision material for the Superior 
            Algebra course

          **Tech stack**
          - `CAD` AutoCAD, MS Visio
          - `Chemical drawing` ChemSketch
          - `Data analysis` OriginLab
          - `LaTeX`
          - `Mathematics` Maple, Mathcad, Polymath
          - `Process simulation` Aspen HYSYS, Aspen HTFS

      - title: "Java Programming MOOC"
        school:
          name: "University of Helsinki"
          url: "https://java-programming.mooc.fi/"
        date: "Jul 2022 - Oct 2022"
        content: |-
          - Self-learning Java using the MOOC from the University of Helsinki
          - My solutions to the exercises can be found on the 
          [Java I](https://github.com/mariel-rs/mooc_fi_java) and 
          [Java II](https://github.com/mariel-rs/mooc_fi_java_ii) repositories

          **Stack**
          - Java
          - Maven
      - title: "Full Stack Web development training"
        school:
          name: "LaunchX / Inovaccion Virtual"
          url: "https://info.microsoft.com/LA-DevEngage-WBNR-FY22-02Feb-15-Launch-X-SRDEM100737_LP02-On-Demand-Registration---Form-in-Body.html"
        date: "Feb 2022 - May 2022"
        content: |-
          - 3 months web development training program sponsored by Microsoft 
          Mexico

          **Stack**
          - HTML
          - CSS
          - JavaScript
          - NodeJS

      #   featuredLink:
      #     enable: false
      #     name: "My academic record"
      #     url: "https://example.com"
      # - title: "High School"
      #   school:
      #     name: "Thomas Jefferson High School for Science and Technology."
      #     url: "https://example.org"
      #   GPA: "4.2 out of 5.0"
      #   featuredLink:
      #     enable: false
      #     url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Dat Lab
        content: Dat Lab is a website where I publish the content created for the 
          training courses I run. The courses are targeted to people who want to
          supplement their skills and expand their productivity with programming 
          and technology, yet have little to none programming experience. The 
          courses vary from Data Analysis, Introductory Python to Applied
          statistics. This site is in Spanish.
      
        image: /images/projects/datlab.PNG
        featured:
          name: Link to site
          link: http://mariel-rs.github.io/datlab
        badges:
          - "Hugo"
          - "Javascript"
          - "Python"
        # links:
        #   - icon: fa fa-envelope
        #     url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/hugo-profile
        #   - icon: fab fa-twitter
        #     url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Airport slot allocation
        content: A script that assigns a slot to air carrier landing/take-off
         requests to use runways and terminals, considering capacities and IATA
         regulations. The assignment is done heuristically using a greedy
         constructive algorithm, yielding results in seconds. MSc dissertation project.
        image: /images/projects/jupyter_run.png
        # featured:
        #   name: Demo
        #   link: https://example.com
        badges:
          - "Python"
        #   - "Bootstrap"
        #links:
        #   - icon: fas fa-file-pdf
        #     url: https://github.com/

      - title: Facility location for obnoxious sites
        content: A mini case study using real data from a waste management
          system in Central Portugal. The model calculates the number of facilities
          (transfer stations, recycling centers and incinerators) and the best
          location using a mixed-integer linear programming (MILP) model.
        image: /images/projects/antunes.JPG
        # featured:
        #   name: Demo (Binder)
        #   link: https://mybinder.org/v2/gh/mariel-rs/MSW_Portugal/HEAD
        badges:
          - "Python"
          - "Pyomo"
          - "Jupyter notebook"
        links:
          - icon: fab fa-github
            url: https://github.com/mariel-rs/MSW_Portugal

          - icon: fas fa-file-pdf
            url: /doc/TAOR_project.pdf

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you are interested in supplementing
            your operations with analytics or we have similar ideas, feel free 
            to drop a note.
            `mariel [dot] rsal [at] gmail [dot] com`
    #email: gurusabarisha@gmail.com
    #btnName: Mail me

  footer:
    #recentPosts: 1
    socialNetworks:
      github: https://github.com/mariel-rs/
      linkedin: https://www.linkedin.com/in/amreyes12/
